# Generated by Django 4.1.5 on 2023-01-21 14:12

import django.core.validators
from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='名称')),
                ('ipv4_cidr', models.CharField(max_length=18, validators=[network.models.validate_network_ipv4], verbose_name='IPv4 CIDR')),
                ('ipv4_max', models.IntegerField()),
                ('ipv4_min', models.IntegerField()),
                ('vid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4095)], verbose_name='VLAN ID')),
                ('note', models.CharField(blank=True, max_length=64, null=True, verbose_name='メモ')),
            ],
            options={
                'ordering': ['ipv4_cidr'],
            },
        ),
    ]
