# Generated by Django 4.1.5 on 2023-01-22 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['ipv4_min']},
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='ホスト名')),
                ('ipv4', models.CharField(max_length=15, unique=True, validators=[django.core.validators.ip_address_validators], verbose_name='IPv4')),
                ('ipv4_number', models.IntegerField(unique=True)),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.network')),
            ],
            options={
                'ordering': ['ipv4_number'],
            },
        ),
    ]
