# Generated by Django 4.1.5 on 2023-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_network_options_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='network_id',
            new_name='network',
        ),
    ]
